Description: "Second template using python" 
Resources: 
  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement: 
          - Effect: Allow
            Principal: 
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
  DynamoPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: DynamoPolicy
      PolicyDocument: 
        Version: 2012-10-17
        Statement: 
          - Effect: Allow
            Action: dynamodb:UpdateItem 
            Resource: !GetAtt Table.Arn 
      Roles: 
        - !Ref Role
  Function:
    Type: AWS::Lambda::Function
    Properties: 
      Code:
        ZipFile: |
          def handler(event, context):
            return True
      Runtime: python3.7
      Handler: index.handler
      Role: !GetAtt Role.Arn
      Environment: 
        Variables:
          TABLE_NAME: !Ref Table
  Table: 
    Type: AWS::DynamoDB::Table
    Properties:
      ProvisionedThroughput: 
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      AttributeDefinitions:
      - AttributeName: Id 
        AttributeType: S
      KeySchema:
      - AttributeName: Id 
        KeyType: HASH